# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/golangci/golangci-lint
%global goipath         github.com/golangci/golangci-lint
Version:                2.1.6
%global tag             v2.1.6

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Fast linters runner for Go.

It runs linters in parallel, uses caching, supports YAML configuration,
integrates with all major IDEs, and includes over a hundred linters.}

%global golicenses      LICENSE docs/LICENSE third_party/dogsled/LICENSE\\\
                        third_party/gochecknoglobals/LICENSE\\\
                        third_party/gochecknoinits/LICENSE\\\
                        third_party/gometalinter/LICENSE\\\
                        third_party/lll/LICENSE third_party/nakedret/LICENSE\\\
                        third_party/x_tools/LICENSE
%global godocs          docs CHANGELOG.md README.md scripts/bench/readme.md

Name:           golangci-lint
Release:        %autorelease
Summary:        Fast linters runner for Go

License:        MIT AND BSD-3-Clause AND GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                              %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/*          %{buildroot}%{_bindir}/
install -m 0755 -vd                              %{buildroot}%{_pkgdocdir}
install -m 0644 -vp .golangci.reference.yml      %{buildroot}%{_pkgdocdir}/
install -m 0644 -vp .golangci.next.reference.yml %{buildroot}%{_pkgdocdir}/
install -m 0644 -vp .custom.gcl.reference.yml    %{buildroot}%{_pkgdocdir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE docs/LICENSE third_party/dogsled/LICENSE
%license third_party/gochecknoglobals/LICENSE
%license third_party/gochecknoinits/LICENSE third_party/gometalinter/LICENSE
%license third_party/lll/LICENSE third_party/nakedret/LICENSE
%license third_party/x_tools/LICENSE
%doc docs CHANGELOG.md README.md scripts/bench/readme.md
%doc %{_pkgdocdir}/.golangci.reference.yml %{_pkgdocdir}/.golangci.next.reference.yml %{_pkgdocdir}/.custom.gcl.reference.yml
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should not use globs to avoid installing conflicting
# binaries.
# Write a _bindir line per each of the binaries the package will install.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%{_bindir}/%{name}
%endif

%gopkgfiles

%changelog
%autochangelog
