# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://sigs.k8s.io/kind
%global goipath         sigs.k8s.io/kind
%global forgeurl        https://sigs.k8s.io/kind
Version:                0.29.0
%global tag             v0.29.0

%global kindversion      sigs.k8s.io/kind/pkg/cmd/kind/version
%global commit           200b3aac0b5ff698426715db9b4d13288bd470a3
%global commitsSincePrev 9

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
kind is a tool for running local Kubernetes clusters using Docker container
"nodes". kind was primarily designed for testing Kubernetes itself, but may be
used for local development or CI.

kind consists of:
- Go packages implementing cluster creation, image build, etc.
- A command line interface (kind) built on these packages.
- Docker image(s) written to run systemd, Kubernetes, etc.
- kubetest integration also built on these packages (WIP)

kind bootstraps each "node" with kubeadm. For more details see the design documentation.

NOTE: kind is still a work in progress}

%global golicenses      LICENSE hack/third_party/gimme/LICENSE\\\
                        images/base/scripts/third_party/gimme/LICENSE\\\
                        images/kindnetd/LICENSE\\\
                        images/kindnetd/scripts/third_party/gimme/LICENSE\\\
                        images/local-path-\\\
                        provisioner/scripts/third_party/gimme/LICENSE\\\
                        logo/LICENSE site/LICENSE site/static/logo/LICENSE
%global godocs          CONTRIBUTING.md README.md code-of-conduct.md\\\
                        hack/build/README.md hack/ci/README.md hack/ci/push-\\\
                        latest-cli/README.md hack/make-rules/update/README.md\\\
                        hack/make-rules/verify/README.md\\\
                        hack/release/build/README.md\\\
                        hack/third_party/gimme/README.md hack/tools/README.md\\\
                        hack/tools/boilerplate.go.txt images/base/README.md\\\
                        images/base/files/LICENSES/README.txt\\\
                        images/base/files/kind/README.txt\\\
                        images/base/scripts/third_party/gimme/README.md\\\
                        images/haproxy/README.md images/kindnetd/README.md\\\
                        images/kindnetd/files/LICENSES/README.txt\\\
                        images/kindnetd/scripts/third_party/gimme/README.md\\\
                        images/local-path-helper/README.md images/local-path-\\\
                        provisioner/README.md images/local-path-\\\
                        provisioner/files/LICENSES/README.txt images/local-\\\
                        path-provisioner/scripts/third_party/gimme/README.md\\\
                        images/node/README.md site/README.md docs\\\
                        site/content/_index.md docs site/layouts/robots.txt\\\
                        examples

Name:           kind
Release:        %autorelease
Summary:        Kubernetes IN Docker - local clusters for testing Kubernetes

License:        CC-BY-4.0 AND Apache-2.0 AND MIT
URL:            %{gourl}
Source:         %{gosource}

Requires:       podman

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
export LDFLAGS="$LDFLAGS -X=%{kindversion}.gitCommit=%{commit} -X=%{kindversion}.gitCommitCount=%{commitsSincePrev}"
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/kind %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE hack/third_party/gimme/LICENSE
%license images/base/scripts/third_party/gimme/LICENSE images/kindnetd/LICENSE
%license images/kindnetd/scripts/third_party/gimme/LICENSE
%license images/local-path-provisioner/scripts/third_party/gimme/LICENSE
%license logo/LICENSE site/LICENSE site/static/logo/LICENSE
%doc CONTRIBUTING.md README.md code-of-conduct.md hack/build/README.md
%doc hack/ci/README.md hack/ci/push-latest-cli/README.md
%doc hack/make-rules/update/README.md hack/make-rules/verify/README.md
%doc hack/release/build/README.md hack/third_party/gimme/README.md
%doc hack/tools/README.md hack/tools/boilerplate.go.txt images/base/README.md
%doc images/base/files/LICENSES/README.txt images/base/files/kind/README.txt
%doc images/base/scripts/third_party/gimme/README.md images/haproxy/README.md
%doc images/kindnetd/README.md images/kindnetd/files/LICENSES/README.txt
%doc images/kindnetd/scripts/third_party/gimme/README.md
%doc images/local-path-helper/README.md images/local-path-provisioner/README.md
%doc images/local-path-provisioner/files/LICENSES/README.txt
%doc images/local-path-provisioner/scripts/third_party/gimme/README.md
%doc images/node/README.md site/README.md docs site/content/_index.md docs
%doc site/layouts/robots.txt examples
%{_bindir}/kind
%endif

%gopkgfiles

%changelog
%autochangelog
